version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    groups:
      dependencies:
        dependency-type: "production"
        patterns: ['*']
      dev-dependencies:
        dependency-type: "development"
        patterns: ['*']

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      dependencies:
        patterns: ['*']
