version: "2"

checks:
  similar-code:
    enabled: false
  method-complexity:
    config:
      threshold: 9

engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
    - src/**.php
