name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Get yarn cache directory
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache yarn dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: node_modules/.bin/read-changelog > PUBLISH.txt

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: PUBLISH.txt
