name: Tests

on:
  # schedule: # scheduled to run at 23.00 on Saturday (UTC), means 6.00 on Monday (WIB)
  #   - cron: '0 23 * * 6'
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - .github/workflows/*.yml
      - composer.*
      - src/*
      - tests/*

jobs:
  prepare:
    name: Prepare
    uses: feryardiant/actions/.github/workflows/configure.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  tests:
    name: Runs on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    needs: prepare
    env:
      GIT_COMMIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ needs.prepare.outputs.composer-cache }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: composer test

      - name: Generate reports for CodeClimate
        if: needs.prepare.outputs.has-codeclimate == 'true'
        id: reports
        env:
          CODECLIMATE_REPORT: tests/codeclimate.${{ matrix.php }}.json
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          CC_TEST_REPORTER_URL: ${{ vars.CC_TEST_REPORTER_URL }}
        run: |
          curl -LSs $CC_TEST_REPORTER_URL > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov -o $CODECLIMATE_REPORT tests/lcov.info

      - name: Generate reports for Coveralls
        if: needs.prepare.outputs.has-coveralls == 'true'
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: php-${{ matrix.php }}
          file: tests/lcov.info
          parallel: true

      - name: Save Coverage Reports
        if: needs.prepare.outputs.has-codeclimate == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.php }}
          path: tests/codeclimate.*.json

  reports:
    name: Reports
    needs: [prepare, tests]
    if: needs.prepare.outputs.should-reports == '1'
    uses: feryardiant/actions/.github/workflows/report.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    with:
      has-coveralls: ${{ needs.prepare.outputs.has-coveralls == 'true' }}
      has-codeclimate: ${{ needs.prepare.outputs.has-codeclimate == 'true' }}
